# Linear Algebra

Sources: [Deep Learning](www.deeplearningbook.org)

In [1]:
# Library imports
import numpy as np

Definitions and notation:

- **Scalar**: a single number, such as $s \in \mathbb{R}$ or $n \in \mathbb{N}$.
- **Vector**: an array of numbers in order. If each element $x_i \in \mathbb{R}$ for vector $\mathbf{a}$, then vector $\mathbf{a}$ lies in set $\mathbb{R}^n$. Vectors in machine learning are typically column vectors (shape $n \times 1$). You can think of vectors as identifying points in space, with each element giving the coordinate along a different axis.

\begin{align}
\mathbf{a} = \sum_{i=1}^n a_i b_i
\end{align}

- **Matrix**: 2D array of numbers, each element has two indices. A matrix $\mathbf{A}$ with $m$ rows and $n$ columns, then $\mathbf{A} \in \mathbb{R}^{m \times n}$. Elements of a matrix are identified as $A_{i, j}$ where the subscripts identify the $i$-th row and $j$-th column for the item.

\begin{align}
\mathbf{A} = \begin{bmatrix}
A_{1, 1} & A_{1, 2} \\
A_{2, 1} & A_{2, 2} 
\end{bmatrix}
\end{align}

- **Tensor**: an array $\mathsf{A}$ with more than two axes. Elements are identified by $\mathsf{A}_{i, j, k}$.
- **Transpose**: the transpose of a matrix is the mirror image of the matrix across the main diagonal (running down and to right):

\begin{align}
\mathbf{A} = \begin{bmatrix}
A_{1, 1} & A_{1, 2} \\
A_{2, 1} & A_{2, 2} \\
A_{3, 1} & A_{3, 2}
\end{bmatrix} \Rightarrow
\mathbf{A}^\mathsf{T} = \begin{bmatrix}
A_{1, 1} & A_{2, 1} & A_{3, 1} \\
A_{1, 2} & A_{2, 2} & A_{3, 2} 
\end{bmatrix}
\end{align}

- The **dot product** of two vectors $\mathbf{a}$ and $\mathbf{b}$ of the same dimensionality is defined as the sum of the element-wise products:

\begin{align}
\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^n a_i b_i
\end{align}

- **Matrix multiplication** of $A$ and $B$ only works if $A$ has the same number of columns as $B$ has rows. So if $A$ is $m \times n$ and $B$ is $n \times p$, the result $C$ is of shape $m \times p$

$$
C_{i, j} = \sum_k \mathbf{A}_{i, k} \mathbf{B}_{k, j}
$$

- An element-wise product, or **Hadamard product**, multiplies each element ($\mathbf{A} \odot \mathbf{B}$)
- A system of equations can be written as $\mathbf{Ax} = \mathbf{b}$, where $\mathbf{A} \in \mathbb{R}^{m \times n}$ is a known matrix, $\mathbf{b} \in \mathbb{R}^{m}$ is a known vector, and $\mathbf{x} \in \mathbb{R}^{n}$ is a vector of unknown variables to solve for.

In [8]:
# Vectors and dot products
a = np.array([1, 2, 3, 4]).reshape(4,)
print('Vector a:', a)

b = np.array([1, 0, 2, 1]).reshape(4,)
print('Vector b:', b)

print('Dot product of a and b:', np.dot(a, b))

Vector a: [1 2 3 4]
Vector b: [1 0 2 1]
Dot product of a and b: 11


In [13]:
# Matrix multiplication
A = np.array([5, 2, 10, 1, 0, 7]).reshape(3, 2)
print('Matrix A:')
print(A)

B = np.array([1, 3, 0, 1]).reshape(2, 2)
print('Matrix B:')
print(B)

print('AB =')
print(np.matmul(A, B))

Matrix A:
[[ 5  2]
 [10  1]
 [ 0  7]]
Matrix B:
[[1 3]
 [0 1]]
AB =
[[ 5 17]
 [10 31]
 [ 0  7]]


## Matrix Multiplication Properties

Matrix multiplication is both distributive $\mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C}$ as well as associative $\mathbf{A}(\mathbf{B} \mathbf{C}) = (\mathbf{A}\mathbf{B}) \mathbf{C}$.

However, matrix multiplication is NOT commutative $\mathbf{A} \mathbf{B} \ne \mathbf{B} \mathbf{A}$. That said, the dot product between two vectors is commutative: $\mathbf{x}^{\mathsf{T}} \mathbf{y} = \mathbf{y}^{\mathsf{T}} \mathbf{x}$.

The transpose of a matrix product can be written as $\mathbf{AB}^{\mathsf{T}} = \mathbf{B}^{\mathsf{T}} \mathbf{A}^{\mathsf{T}}$.

In [14]:
# Transposes
print('Matrix A:')
print(A)
print('Transpose of A:')
print(A.T)

Matrix A:
[[ 5  2]
 [10  1]
 [ 0  7]]
Transpose of A:
[[ 5 10  0]
 [ 2  1  7]]


In [15]:
print('Vector a:')
print('Vector b:')
print('Tranpose of a dot b:')
print(np.dot(a.T, b))
print('Tranpose of b dot a:')
print(np.dot(b.T, a))

Vector a:
Vector b:
Tranpose of a dot b:
11
Tranpose of b dot a:
11


In [16]:
# Distributive property
C = np.array([4, 4, 0, 1]).reshape(2, 2)
print('A(B + C):')
print(np.matmul(A, B+C))

print('AB + AC:')
print(np.matmul(A, B) + np.matmul(A, C))

A(B + C):
[[25 39]
 [50 72]
 [ 0 14]]
AB + AC:
[[25 39]
 [50 72]
 [ 0 14]]


In [17]:
# Associative property
print('A(BC):')
print(np.matmul(A, np.matmul(B, C)))

print('(AB)C:')
print(np.matmul(np.matmul(A, B), C))

A(BC):
[[20 37]
 [40 71]
 [ 0  7]]
(AB)C:
[[20 37]
 [40 71]
 [ 0  7]]


## Identity and Inverse Matrices

The **identity matrix** is a matrix that does not change any vector when you multiply the vector by that matrix. The identity matrix that preserves $n$-dimensional vectors is denoted $\mathbf{I}_n$:

\begin{align}
\mathbf{I}_n \in \mathbb{R}^{n \times n} \text{and } \forall \mathbf{x} \in \mathbb{R}^n, \, \mathbf{I}_n \mathbf{x} = \mathbf{x}
\end{align}

The structure of an identity matrix has $1$'s along the main diagonal and zeroes for all other entries. For example:

\begin{align}
\mathbf{I}_3 = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
\end{align}

A **matrix inverse** of $\mathbf{A}$ is written as $\mathbf{A}^{-1}$ and is defined so $\mathbf{A}^{-1} \mathbf{A} = \mathbf{I}_n$. It's also possible to define an inverse that's multiplied on the right, such that $\mathbf{A} \mathbf{A}^{-1} = \mathbf{I}_n$. For square matrices ($m = n$), the left and right inverses are the same.

This is useful in theory to solve a system of linear equations $\mathbf{Ax} = \mathbf{b}$, where the solution is $\mathbf{x} = \mathbf{A}^{-1} \mathbf{b}$. This assumes that the inverse exists, for that to happen, the equation $\mathbf{Ax} = \mathbf{b}$ has exactly one solution (versus no solutions or an infinite number of solutions).

In [19]:
I4 = np.eye(4)
print('Identity matrix (4x4):')
print(I4)

print('Vector a:')
print(a)

print('I_4 * a:')
print(np.matmul(I4, a))

Identity matrix (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Vector a:
[1 2 3 4]
I_4 * a:
[1. 2. 3. 4.]


## Linear Combinations and Span

A **linear combination** of a set of vectors $\{\mathbf{v}^{(1)}, \ldots , \mathbf{v}^{(n)} \}$ is given be multiplying each vector $\mathbf{v}^{(i)}$ by a scalar and adding the results:

\begin{align}
\displaystyle \sum_i = c_i \mathbf{v}^{(i)}
\end{align}

The **span** of a set of vectors is the set of all points obtainable by linear combination of the original vectors.